admins: []
forwards:
- dest:
  - -1001265168488
  end: null
  offset: '0'
  source: -1001217854936
live:
  delete_on_edit: null
  delete_sync: false
past:
  delay: 0
plugins:
  filter:
    files:
      whitelist:
      - document
   show_forwarded_from: false
  replace:
    text:
      @Movie_wrd : @OB_MOVIEZGROUP
     

      # valid types are 
      # audio,gif,video,video_note,sticker,contact,photo,document,nofile
