admins: []
forwards:
- dest:
  - -100e432432
  end: null
  offset: '6667'              #message Id
  source: -10034234
  delete_on_edit: null
  delete_sync: false
past:
  delay: 0
plugins:
  filter:
    files:
      whitelist:
      - audio
      - video
      - contact
      - document
      - nofile
      - photo
show_forwarded_from: false

      # valid types are 
      # audio,gif,video,video_note,sticker,contact,photo,document,nofile
